### ISSUE TITLE
REST service not working

### ISSUE THREAD

**Issue by sntcristian** [SapienzaNLP/extend#1]
Hi, 

I tried to run a REST service with the docker image that you make available. However, I do not receive any result when I try to disambiguate even simple sentences.

_Example:_

`resp = requests.post(url="http://127.0.0.1:22002/", data='[{"text":"Bob Dylan is a famous singer."}]')`

The json result is 

`[{'text': 'Bob Dylan is a singer.', 'disambiguated_entities': []}]`

**Comment by poccio** [comment]
This is a known issue that arises from our pre-computed mention inventory. Mostly for simplicity in this first release, we computed it only on the AIDA-CoNLL dataset, but this resulted in an inventory that is just too small (it covers only ~6k mentions).

I just uploaded a few more comprehensive new ones and updated the README with the corresponding links. I also updated both the [HuggingFace Space demo](https://huggingface.co/spaces/poccio/ExtEnD) and the docker image (poccio/extend:1.0.1). Your query is now correctly handled. For instance, using poccio/extend:1.0.1, the json result I get is:

```
[{'text': 'Bob Dylan is a famous singer.', 'disambiguated_entities': [{'char_start': 0, 'char_end': 9, 'mention': 'Bob Dylan', 'entity': 'Bob Dylan'}]}]
```
