### ISSUE TITLE
Spacy example returns None

### ISSUE THREAD

**Issue by Valdegg** [SapienzaNLP/extend#2]
Hi, I'm trying out your system and after installing everything the right way (some packages needed to be down/upgraded), I ran the spacy example on the longformer with le&titov's candidate sets.

The code is the following and the output warning message is below.

It says that dataset.base is empty. Might that be the problem?

Output: [('Japan', None), ('Syria', None), ('Friday', None)]

````
import spacy
from extend import spacy_component

nlp = spacy.load("en_core_web_sm")

extend_config = dict(
    checkpoint_path="../extend-longformer-large/2021-10-22/09-11-39/checkpoints/best.ckpt",
    mentions_inventory_path="../le-and-titov-2018-inventory.min-count-2.sqlite3",
    device=0,
    tokens_per_batch=4000,
)

nlp.add_pipe("extend", after="ner", config=extend_config)

input_sentence = "Japan began the defence of their title " \
                 "with a lucky 2-1 win against Syria " \
                 "in a championship match on Friday."

doc = nlp(input_sentence)

# [(Japan, Japan National Footbal Team), (Syria, Syria National Footbal Team)]
disambiguated_entities = [(ent.text, ent._.disambiguated_entity) for ent in doc.ents]






2022-05-05 13:39:07.458 WARNING classy.data.dataset.base: Token batch size 4000 < max length 4096. This might result in batches with only 1 sample that contain more token than the specified token batch size
2022-05-05 13:39:07.459 WARNING classy.data.dataset.base: Dataset empty

````

**Comment by poccio** [comment]
Hi, that warning message is indeed the problem. It means that the underlying torch dataset was empty, that is, no tokens to disambiguate were passed to the model. I'm trying to reproduce your issue but, even running your snippet, I get both Japan and Syria disambiguated.

Can you provide us more details on the environment you are using? Especially the extend and classy-core versions.
